$env:CP_ID="CP003"
$env:CP_LOCATION="Paris"
$env:CP_PRICE="0.38"
$env:REGISTRY_URL="http://localhost:8000/api/registry"
$env:CENTRAL_HOST="localhost"
$env:CENTRAL_PORT="5001"
$env:ENGINE_HOST="localhost"
$env:ENGINE_PORT="9301"
$env:ENGINE_MONITOR_PORT="6062"
python main.py
